In [51]:
import matplotlib.pyplot as plt
import spikeinterface as si
import spikeinterface.extractors as se
import spikeinterface.postprocessing as spost
import spikeinterface.widgets as sw
import numpy as np
from pathlib import Path
import shutil

In [31]:
wave_a = np.load('C:\waveforms\waveforms/waveforms_1.npy')
wave_a_index = np.load('C:\waveforms\waveforms/sampled_index_1.npy')

In [ ]:
import pickle
import pandas as pd

# Load the pickle file
with open(r'S:/Sachuriga/Ephys_Vedio/CR_CA1/raw_files/63383_Open_Field_50Hz_A2024-07-13T14_10_11DLC_DlcrnetStride32Ms5_CR_implant_DLCnetNov30shuffle1_snapshot_350_sk.pickle', 'rb') as file:
    data = pickle.load(file)

# Check the type and contents
print("Type of data:", type(data))
print("Contents of data:", data)


In [ ]:
data[0][0][1][]

array([35.84500122, 51.63199997,  0.99900001, -1.        ])

In [21]:
data['scorer', 'individual1']

KeyError: ('scorer', 'individual1')

In [ ]:
for row in data[0]:
    

array([[  6.954     ,  32.15499878,   0.98900002,  -1.        ],
       [ 35.84500122,  51.63199997,   0.99900001,  -1.        ],
       [ 39.19900131,  20.15099907,   0.99800003,  -1.        ],
       [ 24.31999969,  35.05400085,   0.99900001,  -1.        ],
       [ 35.60599899,  35.85900116,   0.99900001,  -1.        ],
       [ 47.53900146,  34.69800186,   0.99900001,  -1.        ],
       [ 58.04499817,  32.95999908,   0.99900001,  -1.        ],
       [ 69.27400208,  31.31800079,   0.99800003,  -1.        ],
       [ 78.97699738,  29.48200035,   0.99800003,  -1.        ],
       [ 90.02600098,  27.58399963,   0.99900001,  -1.        ],
       [114.15299988,  28.16600037,   0.99599999,  -1.        ],
       [135.73800659,  33.60100174,   0.99400002,  -1.        ],
       [160.50999451,  39.09600067,   0.98900002,  -1.        ]])

In [47]:
dlc_path = Path("S:\Sachuriga\Ephys_Vedio\CR_CA1/65165_Open_Field_50Hz_A2023-06-29T17_03_02DLC_dlcrnetms5_CR_implant_DLCnetNov30shuffle3_600000_sk_filtered.h5")

In [63]:
temp_vname = dlc_path.name.split("DLC_dlcrnet")
vname=temp_vname[0]
path_ori = dlc_path.parent
idun_vedio_path=r"P:/Overlap_project/data/CR_implant_add_new"

In [4]:
cd Q:\sachuriga\Sachuriga_Python\quattrocolo-nwb4fp\src

Q:\sachuriga\Sachuriga_Python\quattrocolo-nwb4fp\src


c:\Users\sachur\AppData\Local\anaconda3\envs\nwb4fp\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [27]:
import sys
sys.path.append(r"Q:/sachuriga/Sachuriga_Python/quattrocolo-nwb4fp/src/")
from pickle import TRUE
import spikeinterface as si
import spikeinterface.extractors as se
import spikeinterface.postprocessing as post
from nwb4fp.postprocess.Get_positions import load_positions,load_positions_h5,test_positions_h5
from nwb4fp.postprocess.get_potential_merge import get_potential_merge
from spikeinterface.preprocessing import (bandpass_filter,
                                           common_reference,
                                           whiten)
import spikeinterface.exporters as sex
import spikeinterface.qualitymetrics as sqm
from pathlib import Path
import pandas as pd
from nwb4fp.postprocess.extract_wf import wf4unim,divide_wf
import spikeinterface.preprocessing as spre
import numpy as np

from spikeinterface.extractors.neoextractors.openephys import OpenEphysBinaryRecordingExtractor


In [ ]:
path=r"S:\Sachuriga/Ephys_Recording/CR_CA1/63383/63383_2024-07-20_14-21-42_A_phy_k"
global_job_kwargs = dict(n_jobs=32, total_memory="64G",mp_context= "spawn",progress_bar=True)
si.set_global_job_kwargs(**global_job_kwargs)
temp_folder = r"C:/Ephys_temp"

sorting = se.read_phy(folder_path=path, load_all_cluster_properties=True,exclude_cluster_groups = ["noise", "mua"])

temp_path = path.split("_phy")
raw_path = temp_path[0]
#stream_name = 'Record Node 101#OE_FPGA_Acquisition_Board-100.Rhythm Data'
stream_name  = OpenEphysBinaryRecordingExtractor(raw_path,stream_id='0').get_streams(raw_path)[0][0]
print(fr"Before mannual search the stream_name. Auto search result is {stream_name}")
try:
    recording = se.read_openephys(raw_path, stream_name=stream_name, load_sync_timestamps=True)
except AssertionError:
    try:
        stream_name = 'Record Node 102#OE_FPGA_Acquisition_Board-101.Rhythm Data'
        recording = se.read_openephys(raw_path, stream_name=stream_name, load_sync_timestamps=True)
    except AssertionError:
        stream_name = 'Record Node 101#Acquisition_Board-100.Rhythm Data'
        recording = se.read_openephys(raw_path, stream_name=stream_name, load_sync_timestamps=True)

import probeinterface as pi

# from probeinterface import plotting
manufacturer = 'cambridgeneurotech'
probe_name = 'ASSY-236-F'
probe = pi.get_probe(manufacturer, probe_name)
print(probe)
# probe.wiring_to_device('cambridgeneurotech_mini-amp-64')
# map channels to device indices
mapping_to_device = [
    # connector J2 TOP
    41, 39, 38, 37, 35, 34, 33, 32, 29, 30, 28, 26, 25, 24, 22, 20,
    46, 45, 44, 43, 42, 40, 36, 31, 27, 23, 21, 18, 19, 17, 16, 14,
    # connector J1 BOTTOM
    55, 53, 54, 52, 51, 50, 49, 48, 47, 15, 13, 12, 11, 9, 10, 8,
    63, 62, 61, 60, 59, 58, 57, 56, 7, 6, 5, 4, 3, 2, 1, 0
]

probe.set_device_channel_indices(mapping_to_device)
probe.to_dataframe(complete=True).loc[:, ["contact_ids", "shank_ids", "device_channel_indices"]]
probegroup = pi.ProbeGroup()
probegroup.add_probe(probe)

pi.write_prb(f"{probe_name}.prb", probegroup, group_mode="by_shank")
recording_prb = recording.set_probe(probe, group_mode="by_shank")
rec = bandpass_filter(recording_prb, freq_min=300, freq_max=8000)
bad_channel_ids, channel_labels = spre.detect_bad_channels(rec, method='coherence+psd',n_neighbors = 9)
#recording_good_ch= rec.remove_channels(bad_channel_ids)
recording_good_channels_f = spre.interpolate_bad_channels(rec,bad_channel_ids)

rec_save = common_reference(recording_good_channels_f, reference='global', operator='median')
rec_w = whiten(rec_save, int_scale=200, mode='local', radius_um=100.0)
                
sorting.set_property(key='group', values = sorting.get_property("channel_group"))
print(f"get times for raw sorts{sorting.get_times()}")
## step to analyzer
GLOBAL_KWARGS = dict(n_jobs=8, total_memory="64G", progress_bar=True, mp_context= "spawn", chunk_size=5000, chunk_duration="1s")
si.set_global_job_kwargs(**GLOBAL_KWARGS)

analyzer = si.create_sorting_analyzer(sorting=sorting, recording=rec_w, format='memory', folder=fr"{temp_folder}",overwrite=True)
## step to computations
GLOBAL_KWARGS = dict(n_jobs=12, total_memory="64G", progress_bar=True, mp_context= "spawn", chunk_size=5000, chunk_duration="1s")
si.set_global_job_kwargs(**GLOBAL_KWARGS)
we1 = analyzer.compute("random_spikes","waveforms")
we1 = analyzer.compute("waveforms")
we1 = analyzer.compute("noise_levels")
we1 = analyzer.compute("templates")
#get potential merging sorting objects
print("processing potential merge...\n")

Before mannual search the stream_name. Auto search result is Record Node 101#Acquisition_Board-100.Rhythm Data
ASSY-236-F - cambridgeneurotech - 64ch - 6shanks
get times for raw sortsNone


compute_waveforms (workers: 12 processes): 100%|██████████| 7477/7477 [00:06<00:00, 1092.69it/s]
c:\Users\sachur\AppData\Local\anaconda3\envs\nwb4fp\lib\site-packages\spikeinterface\core\recording_tools.py:786: UserWarning: get_noise_levels(recording, num_chunks_per_segment=20) is deprecated
Now, you need to use get_noise_levels(recording, random_slices_kwargs=dict(num_chunks_per_segment=20, chunk_size=1000))
Please read get_random_recording_slices() documentation for more options.
  warnings.warn(msg)
noise_level (workers: 12 processes): 100%|██████████| 20/20 [00:01<00:00, 16.96it/s]


processing potential merge...



In [30]:
recording_good_channels_f.get_channel_ids()

array(['CH1', 'CH2', 'CH3', 'CH4', 'CH5', 'CH6', 'CH7', 'CH8', 'CH9',
       'CH10', 'CH11', 'CH12', 'CH13', 'CH14', 'CH15', 'CH16', 'CH17',
       'CH18', 'CH19', 'CH20', 'CH21', 'CH22', 'CH23', 'CH24', 'CH25',
       'CH26', 'CH27', 'CH28', 'CH29', 'CH30', 'CH31', 'CH32', 'CH33',
       'CH34', 'CH35', 'CH36', 'CH37', 'CH38', 'CH39', 'CH40', 'CH41',
       'CH42', 'CH43', 'CH44', 'CH45', 'CH46', 'CH47', 'CH48', 'CH49',
       'CH50', 'CH51', 'CH52', 'CH53', 'CH54', 'CH55', 'CH56', 'CH57',
       'CH58', 'CH59', 'CH60', 'CH61', 'CH62', 'CH63', 'CH64'],
      dtype='<U64')

In [25]:
print(sorting.count_num_spikes_per_unit())

{18: 50250, 27: 402, 1: 8249, 28: 4047, 2: 1191, 3: 1899, 6: 769, 7: 31923, 8: 6372, 10: 37359, 11: 17056, 12: 2877, 15: 2785, 29: 1788, 16: 1393, 20: 1583, 23: 56217, 24: 4180, 26: 986}


In [26]:
sort_merge = get_potential_merge(sorting, analyzer)
print(sort_merge.count_num_spikes_per_unit())

get_potential_merge
{18: 50249, 27: 402, 1: 8248, 3: 1899, 6: 769, 7: 31922, 8: 6372, 10: 37357, 11: 17056, 12: 2877, 15: 2785, 29: 1788, 16: 1392, 20: 1583, 23: 56217, 24: 4180, 26: 986, 30: 5238}


In [9]:
a=sorting.get_property_keys()
print(a)

['original_cluster_id', 'amp', 'amplitude_cutoff', 'amplitude_median', 'ch', 'd_prime', 'depth', 'firing_range', 'fr', 'quality', 'isi_violations_count', 'isi_violations_ratio', 'isolation_distance', 'l_ratio', 'n_spikes', 'nn_hit_rate', 'nn_miss_rate', 'presence_ratio', 'rp_contamination', 'rp_violations', 'sh', 'silhouette', 'sliding_rp_violation', 'snr', 'sync_spike_2', 'sync_spike_4', 'sync_spike_8']


In [11]:
a = sorting.get_property("ch")
a

array([ 7, 48,  0,  0,  0,  0,  8, 14, 14, 17, 22, 22, 30, 30, 30, 29, 39,
       39, 48], dtype=int64)